# Generated by Django 3.1.6 on 2021-03-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SearchKeys', models.TextField()),
                ('TweetNumber', models.IntegerField()),
                ('Chart', models.ImageField(upload_to='Charts')),
                ('Positive', models.IntegerField()),
                ('Negative', models.IntegerField()),
            ],
        ),
    ]
