# Generated by Django 3.1.6 on 2021-03-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetmodel',
            name='Negative',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tweetmodel',
            name='Positive',
            field=models.IntegerField(null=True),
        ),
    ]
