# Generated by Django 3.1.6 on 2021-03-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20210317_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetmodel',
            name='Negative',
        ),
        migrations.RemoveField(
            model_name='tweetmodel',
            name='Positive',
        ),
        migrations.AlterField(
            model_name='tweetmodel',
            name='Chart',
            field=models.ImageField(upload_to='Pictures'),
        ),
    ]
